services:
  backend:
    container_name: backend
    build: .
    volumes:
      - .:/usr/src/
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${POSTGRES_DATA_DIRECTORY}
    volumes:
      - blog_drf_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
volumes:
  blog_drf_data:
